# Generated by Django 3.2.4 on 2021-09-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='test',
            new_name='text',
        ),
    ]
